#!/bin/bash

docker ps -q -a --filter label=service=redistry-prod --filter status=created --filter status=exited --filter status=dead | \
tail -n +6 | while read -r container_id; do
  echo "Attempting to remove container: $container_id"
  if ! docker rm "$container_id"; then
    echo "Failed to remove container: $container_id. Retrying..."
    sleep 5
    docker rm "$container_id"
  fi
done

