# Name of your application. Used to uniquely configure containers.
service: redistry-prod

# Name of the container image.
image: redistry-prod

# Deploy to these servers.
servers:
  web:
    - 5.161.176.178

# If using something like Cloudflare, it is recommended to set encryption mode 
# in Cloudflare's SSL/TLS setting to "Full" to enable end-to-end encryption. 
proxy: 
  ssl: true
  host: redistry.crionlabs.com
  forward_headers: true

# Credentials for your image host.
registry:
  server: REGISTRY_SERVER
  username: AWS
  password:
    - KAMAL_REGISTRY_PASSWORD



# Configure builder setup.
builder:
  arch: amd64
  cache:
    type: gha
    options: mode=max
    image: app-build-cache
  dockerfile: "./Dockerfile"
  context: "./"


sshkit:
  pool_idle_timeout: 300


env:
  secret:
    - KAMAL_REGISTRY_PASSWORD
    - REDIS_HOST
    - REDIS_PORT



accessories:
  redis:
    host: WEB_SERVER_IP
    image: "redis:alpine"
    port: "127.0.0.1:6379:6379"
